---
site_name: Peagen
repo_url: https://github.com/swarmauri/swarmauri-sdk/tree/mono/dev/pkgs/standards/peagen
repo_name: swarmauri/peagen
theme:
  name: material
  logo: assets/swarmauri_logo_dark.jpeg
  favicon: assets/swarmauri_logo_dark.jpeg
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: orange
      accent: deep purple
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: orange
      accent: deep orange
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  icon:
    repo: fontawesome/brands/github
plugins:
  - mkdocstrings:
      handlers:
        python:
          paths:
            - ../../pkgs/standards/peagen
          options:
            extensions:
              - griffe_typingdoc
            show_root_heading: true
            show_if_no_docstring: true
            inherited_members: true
            members_order: source
            separate_signature: true
            unwrap_annotated: true
            filters:
              - '!^_'
            merge_init_into_class: true
            docstring_section_style: spacy
            signature_crossrefs: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_source: true
  - search: null
  - autorefs: null
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: __PYTHON_TAG_0__
  - pymdownx.tabbed:
      alternate_style: true
  - abbr
  - attr_list
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/swarmauri/peagen
nav:
  - Home: index.md
