[pytest]
testpaths =
    v4/tests/spec
norecursedirs =
    combined
    scripts
markers =
    test: standard test
    unit: Unit tests
    i9n: Integration tests
    r8n: Regression tests
    timeout: mark test to timeout after X seconds
    xpass: Expected passes
    xfail: Expected failures
    acceptance: Acceptance tests
    perf: Performance tests that measure execution time and resource usage
timeout = 300
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)s] %(message)s
log_cli_date_format = %Y-%m-%d %H:%M:%S
asyncio_default_fixture_loop_scope = function
