[pytest]
markers =
    test: standard test
    unit: Unit tests
    i9n: Integration tests
    r8n: Regression tests
    timeout: mark test to timeout after X seconds
    xpass: Expected passes
    xfail: Expected failures
    acceptance: Acceptance tests
    perf: Performance tests that measure execution time and resource usage
