[pytest]
markers =
    acceptance: Acceptance tests
    i9n: Integration tests
    perf: Performance tests that measure execution time and resource usage
    r8n: Regression tests
    test: Standard test
    timeout: mark test to timeout after X seconds
    unit: Unit tests
    xfail: Expected failures
    xpass: Expected passes
