schemaVersion = "1.0.3"

[workspace]
org          = "test"
template_set = "default"
workers      = 4

[vcs]
provider = "github"

# ─────────────────────────── LLM  ───────────────────────────────────────
[llm]
default_provider    = "groq"
default_model_name  = "deepseek-r1-distill-llama-70b"
default_temperature = 0.7
default_max_tokens  = 4096

[llm.groq]
API_KEY   = "${GROQ_API_KEY}"

[secrets]
default_secret = "env"

[secrets.adapters.env]
prefix = ""

# ─────────────────────────── Source Packages ───────────────────────────
[[source_packages]]
name            = "swarmauri_sdk"
type            = "git"                # git | local | bundle | uri
uri             = "https://github.com/swarmauri/swarmauri-sdk.git"
ref             = "mono/dev"           # replaces previous --swarmauri-dev flag
dest            = "swarmauri_sdk"
expose_to_jinja = true

# ────────────────────────── Storage Adapters ───────────────────────────
[storage]
default_storage_adapter = "minio"

[storage.adapters.file]
output_dir = "./peagen_artifacts"

[storage.adapters.minio]
endpoint   = "${MINIO_ENDPOINT}"
bucket     = "test"
access_key = "${MINIO_ACCESS_KEY}"
secret_key = "${MINIO_SECRET_KEY}"
secure     = false

# ───────────────────────────── Publishers ──────────────────────────────
[publishers]
default_publisher = "redis"

[publishers.adapters.redis]
host     = "${REDIS_HOST}"
port     = "${REDIS_PORT}"
db       = "${REDIS_DB}"
password = "${REDIS_PASSWORD}"                   # leave blank if no auth

[publishers.adapters.webhook]
url = "${WEBHOOK_URL}"

# ─────────────────────────────── Queues ───────────────────────────────
[queues]
default_queue = "redis"

[queues.adapters.redis]
uri = "${REDIS_URL}"

# ─────────────────────────────── Mutators ───────────────────────────────
[mutators]
default_mutator = "peagen.plugins.mutators.default_mutator:DefaultMutator"


# ───────────────────────────── Result Backends ─────────────────────────
[result_backends]
default_backend = "postgres"

[result_backends.adapters.postgres]
dsn = "${PG_DSN}"


# ────────────────────────────── Evaluation ───────────────────────────────
[evaluation]
pool = "peagen.plugins.evaluator_pools.default:DefaultEvaluatorPool"
max_workers = 4
async = false
strict = true

[evaluation.evaluators]
performance = "peagen.plugins.evaluators.performance_evaluator:PerformanceEvaluator"
