[tool.poetry]
name = "swarmauri-monorepo"
version = "0.6.2.dev3"
description = "Monorepo for multiple interdependent Swarmauri Python packages"
authors = ["Jacob Stewart <jacob@swarmauri.com>"]
# Disables packaging mode
package-mode = false

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
pydantic = "^2.0"
ipython = "^8.28.0"

# Path dependencies (editable installs by default)
###
# Foundational 
###
swarmauri_core = { git = "https://github.com/swarmauri/swarmauri-sdk.git", branch = "mono/dev", subdirectory = "pkgs/core" }
swarmauri_base = { git = "https://github.com/swarmauri/swarmauri-sdk.git", branch = "mono/dev", subdirectory = "pkgs/base" }
swarmauri_standard = { git = "https://github.com/swarmauri/swarmauri-sdk.git", branch = "mono/dev", subdirectory = "pkgs/swarmauri_standard" }
swarmauri = { git = "https://github.com/swarmauri/swarmauri-sdk.git", branch = "mono/dev", subdirectory = "pkgs/swarmauri" }

###
# Extra First Class Citizens
###
swarmauri_vectorstore_doc2vec = { git = "https://github.com/swarmauri/swarmauri-sdk.git", branch = "mono/dev", subdirectory = "pkgs/standards/swarmauri_vectorstore_doc2vec"}
swarmauri_embedding_doc2vec = { git = "https://github.com/swarmauri/swarmauri-sdk.git", branch = "mono/dev", subdirectory = "pkgs/standards/swarmauri_embedding_doc2vec"}
swarmauri_embedding_tfidf = { git = "https://github.com/swarmauri/swarmauri-sdk.git", branch = "mono/dev", subdirectory = "pkgs/standards/swarmauri_embedding_tfidf"}
swarmauri_embedding_nmf = { git = "https://github.com/swarmauri/swarmauri-sdk.git", branch = "mono/dev", subdirectory = "pkgs/standards/swarmauri_embedding_nmf"}
swarmauri_tool_matplotlib = { git = "https://github.com/swarmauri/swarmauri-sdk.git", branch = "mono/dev", subdirectory = "pkgs/standards/swarmauri_tool_matplotlib"}
swarmauri_parser_keywordextractor = { git = "https://github.com/swarmauri/swarmauri-sdk.git", branch = "mono/dev", subdirectory = "pkgs/standards/swarmauri_parser_keywordextractor"}
swarmauri_parser_beautifulsoupelement = { git = "https://github.com/swarmauri/swarmauri-sdk.git", branch = "mono/dev", subdirectory = "pkgs/standards/swarmauri_parser_beautifulsoupelement"}
swarmauri_vectorstore_tfidf = { git = "https://github.com/swarmauri/swarmauri-sdk.git", branch = "mono/dev", subdirectory = "pkgs/standards/swarmauri_vectorstore_tfidf"}
swarmauri_distance_minkowski = { git = "https://github.com/swarmauri/swarmauri-sdk.git", branch = "mono/dev", subdirectory = "pkgs/standards/swarmauri_distance_minkowski"}

# Standard Plugin Example
#swm_example_package = { path = "./standards/swm_example_package" }

###
# Second Class Citizens
###
swarmauri_vectorstore_redis = { git = "https://github.com/swarmauri/swarmauri-sdk.git", branch = "mono/dev", subdirectory = "pkgs/community/swarmauri_vectorstore_redis"}
swarmauri_documentstore_redis = { git = "https://github.com/swarmauri/swarmauri-sdk.git", branch = "mono/dev", subdirectory = "pkgs/community/swarmauri_documentstore_redis"}

swarmauri_vectorstore_qdrant = { git = "https://github.com/swarmauri/swarmauri-sdk.git", branch = "mono/dev", subdirectory = "pkgs/community/swarmauri_vectorstore_qdrant"}
swarmauri_vectorstore_pinecone = { git = "https://github.com/swarmauri/swarmauri-sdk.git", branch = "mono/dev", subdirectory = "pkgs/community/swarmauri_vectorstore_pinecone"}
swarmauri_vectorstore_persistentchromadb = { git = "https://github.com/swarmauri/swarmauri-sdk.git", branch = "mono/dev", subdirectory = "pkgs/community/swarmauri_vectorstore_persistentchromadb"}
swarmauri_vectorstore_neo4j = { git = "https://github.com/swarmauri/swarmauri-sdk.git", branch = "mono/dev", subdirectory = "pkgs/community/swarmauri_vectorstore_neo4j"}
swarmauri_vectorstore_mlm = { git = "https://github.com/swarmauri/swarmauri-sdk.git", branch = "mono/dev", subdirectory = "pkgs/community/swarmauri_vectorstore_mlm"}
swarmauri_vectorstore_duckdb = { git = "https://github.com/swarmauri/swarmauri-sdk.git", branch = "mono/dev", subdirectory = "pkgs/community/swarmauri_vectorstore_duckdb"}
swarmauri_vectorstore_cloudweaviate = { git = "https://github.com/swarmauri/swarmauri-sdk.git", branch = "mono/dev", subdirectory = "pkgs/community/swarmauri_vectorstore_cloudweaviate"}

swarmauri_tool_zapierhook = { git = "https://github.com/swarmauri/swarmauri-sdk.git", branch = "mono/dev", subdirectory = "pkgs/community/swarmauri_tool_zapierhook"}
swarmauri_tool_webscraping = { git = "https://github.com/swarmauri/swarmauri-sdk.git", branch = "mono/dev", subdirectory = "pkgs/community/swarmauri_tool_webscraping"}
swarmauri_tool_textlength = { git = "https://github.com/swarmauri/swarmauri-sdk.git", branch = "mono/dev", subdirectory = "pkgs/community/swarmauri_tool_textlength"}
swarmauri_tool_smogindex = { git = "https://github.com/swarmauri/swarmauri-sdk.git", branch = "mono/dev", subdirectory = "pkgs/community/swarmauri_tool_smogindex"}
swarmauri_tool_sentimentanalysis = { git = "https://github.com/swarmauri/swarmauri-sdk.git", branch = "mono/dev", subdirectory = "pkgs/community/swarmauri_tool_sentimentanalysis"}
swarmauri_tool_sentencecomplexity = { git = "https://github.com/swarmauri/swarmauri-sdk.git", branch = "mono/dev", subdirectory = "pkgs/community/swarmauri_tool_sentencecomplexity"}
swarmauri_tool_qrcodegenerator = { git = "https://github.com/swarmauri/swarmauri-sdk.git", branch = "mono/dev", subdirectory = "pkgs/community/swarmauri_tool_qrcodegenerator"}
swarmauri_tool_lexicaldensity = { git = "https://github.com/swarmauri/swarmauri-sdk.git", branch = "mono/dev", subdirectory = "pkgs/community/swarmauri_tool_lexicaldensity"}
swarmauri_tool_captchagenerator = { git = "https://github.com/swarmauri/swarmauri-sdk.git", branch = "mono/dev", subdirectory = "pkgs/community/swarmauri_tool_captchagenerator"}
swarmauri_tool_downloadpdf = { git = "https://github.com/swarmauri/swarmauri-sdk.git", branch = "mono/dev", subdirectory = "pkgs/community/swarmauri_tool_downloadpdf"}
swarmauri_tool_dalechallreadability = { git = "https://github.com/swarmauri/swarmauri-sdk.git", branch = "mono/dev", subdirectory = "pkgs/community/swarmauri_tool_dalechallreadability"}
swarmauri_tool_gmail = { git = "https://github.com/swarmauri/swarmauri-sdk.git", branch = "mono/dev", subdirectory = "pkgs/community/swarmauri_tool_gmail"}
swarmauri_tool_folium = { git = "https://github.com/swarmauri/swarmauri-sdk.git", branch = "mono/dev", subdirectory = "pkgs/community/swarmauri_tool_folium"}
swarmauri_tool_psutil = { git = "https://github.com/swarmauri/swarmauri-sdk.git", branch = "mono/dev", subdirectory = "pkgs/community/swarmauri_tool_psutil"}
swarmauri_toolkit_github = { git = "https://github.com/swarmauri/swarmauri-sdk.git", branch = "mono/dev", subdirectory = "pkgs/community/swarmauri_toolkit_github"}

swarmauri_state_clipboard = { git = "https://github.com/swarmauri/swarmauri-sdk.git", branch = "mono/dev", subdirectory = "pkgs/community/swarmauri_state_clipboard"}

swarmauri_parser_textblob = { git = "https://github.com/swarmauri/swarmauri-sdk.git", branch = "mono/dev", subdirectory = "pkgs/community/swarmauri_parser_textblob"}
swarmauri_parser_fitzpdf = { git = "https://github.com/swarmauri/swarmauri-sdk.git", branch = "mono/dev", subdirectory = "pkgs/community/swarmauri_parser_fitzpdf"}
swarmauri_parser_entityrecognition = { git = "https://github.com/swarmauri/swarmauri-sdk.git", branch = "mono/dev", subdirectory = "pkgs/community/swarmauri_parser_entityrecognition"}
swarmauri_parser_bertembedding = { git = "https://github.com/swarmauri/swarmauri-sdk.git", branch = "mono/dev", subdirectory = "pkgs/community/swarmauri_parser_bertembedding"}
swarmauri_parser_pypdf2 = { git = "https://github.com/swarmauri/swarmauri-sdk.git", branch = "mono/dev", subdirectory = "pkgs/community/swarmauri_parser_pypdf2"}

swarmauri_measurement_mutualinformation = { git = "https://github.com/swarmauri/swarmauri-sdk.git", branch = "mono/dev", subdirectory = "pkgs/community/swarmauri_measurement_mutualinformation"}
swarmauri_measurement_tokencountestimator = { git = "https://github.com/swarmauri/swarmauri-sdk.git", branch = "mono/dev", subdirectory = "pkgs/community/swarmauri_measurement_tokencountestimator"}

swarmauri_ocr_pytesseract = { git = "https://github.com/swarmauri/swarmauri-sdk.git", branch = "mono/dev", subdirectory = "pkgs/community/swarmauri_ocr_pytesseract"}
swarmauri_embedding_mlm = { git = "https://github.com/swarmauri/swarmauri-sdk.git", branch = "mono/dev", subdirectory = "pkgs/community/swarmauri_embedding_mlm"}


swarmauri_tool_entityrecognition = { git = "https://github.com/swarmauri/swarmauri-sdk.git", branch = "mono/dev", subdirectory = "pkgs/community/swarmauri_tool_entityrecognition"}
swarmauri_llm_leptonai = { git = "https://github.com/swarmauri/swarmauri-sdk.git", branch = "mono/dev", subdirectory = "pkgs/community/swarmauri_llm_leptonai"}
swarmauri_vectorstore_annoy = { git = "https://github.com/swarmauri/swarmauri-sdk.git", branch = "mono/dev", subdirectory = "pkgs/community/swarmauri_vectorstore_annoy"}

#swm_example_community_package = { path = "./community/swm_example_community_package" }



[tool.poetry.group.dev.dependencies]
toml = "^0.10.2"
pytest = "^8.0.0"
pytest-xdist = "^3.6.1"
pytest-asyncio = "0.24.0"

pytest-timeout = "^2.3.1"
pytest-json-report = "^1.5.0"
python-dotenv = "^1.0.0"
pytest-mock = "^3.14.0"
jsonschema = "^4.18.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
norecursedirs = ["experimental"]
asyncio_mode = "auto"

markers = [
    "test: standard test",
    "unit: Unit tests",
    "i9n: Integration tests",
    "r8n: Regression tests",
    "integration: Integration tests",
    "acceptance: Acceptance tests",
    "experimental: Experimental tests",
    "timeout: mark test to timeout after X seconds",
]

log_cli = true
log_cli_level = "INFO"
log_cli_format = "%(asctime)s [%(levelname)s] %(message)s"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"

asyncio_default_fixture_loop_scope = "function"

[tool.ruff]
exclude = ["experimental"]