import pytest
from wcag_pdf_pytest.pdf_inspector import evaluate_sc, SCResult

SC_NUM = "3.2.3"
SC_TITLE = "Consistent Navigation"
SC_LEVEL = "AA"
SC_APPLICABILITY = "Applies"
SC_NOTES = "Autogenerated test for 3.2.3: Consistent Navigation"

@pytest.mark.wcag21
@pytest.mark.AA
def test_sc_3_2_3_consistent_navigation(wcag_pdf_paths, wcag_context):
    assert wcag_pdf_paths, "No --wcag-pdf provided."
    res = evaluate_sc(SC_NUM, SC_TITLE, SC_LEVEL, wcag_pdf_paths, SC_APPLICABILITY, SC_NOTES)
    assert isinstance(res, SCResult)
    assert res.passed, res.reason
