[project]
name = "swarmauri_signing_pgp"
version = "0.1.1.dev3"
description = "OpenPGP envelope signer for Swarmauri"
license = "Apache-2.0"
readme = "README.md"
repository = "http://github.com/swarmauri/swarmauri-sdk"
requires-python = ">=3.10,<3.13"
classifiers = [
    "License :: OSI Approved :: Apache Software License",
    "Natural Language :: English",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Development Status :: 3 - Alpha",
    "Topic :: Security :: Cryptography",
    "Intended Audience :: Developers",
]
authors = [{ name = "Swarmauri", email = "opensource@swarmauri.com" }]
dependencies = [
    "swarmauri_core",
    "swarmauri_base",
    "swarmauri_standard",
    "pgpy>=0.6.0",
]

[project.optional-dependencies]
cbor = ["cbor2>=5.4.6"]

[tool.uv.sources]
swarmauri_core = { workspace = true }
swarmauri_base = { workspace = true }
swarmauri_standard = { workspace = true }

[tool.pytest.ini_options]
norecursedirs = ["combined", "scripts"]
markers = [
    "test: standard test",
    "unit: Unit tests",
    "i9n: Integration tests",
    "r8n: Regression tests",
    "acceptance: Acceptance tests",
    "perf: Performance tests",
]
timeout = 300
log_cli = true
log_cli_level = "INFO"
log_cli_format = "%(asctime)s [%(levelname)s] %(message)s"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
asyncio_default_fixture_loop_scope = "function"

[project.entry-points.'swarmauri.signings']
PgpEnvelopeSigner = "swarmauri_signing_pgp:PgpEnvelopeSigner"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest>=8.0",
    "pytest-asyncio>=0.24.0",
    "pytest-xdist>=3.6.1",
    "pytest-json-report>=1.5.0",
    "python-dotenv",
    "flake8>=7.0",
    "pytest-timeout>=2.3.1",
    "ruff>=0.9.9",
    "pytest-benchmark>=4.0.0",
]
