from __future__ import annotations

class Boot: ...
class Ingress: ...
class Routed: ...
class Bound: ...
class Prepared: ...
class Authorized: ...
class Resolved: ...
class Executing: ...
class Operated: ...
class Encoded: ...
class Emitting: ...
class Egressed: ...
class Failed: ...
