[project]
name = "peagen-storage-github"
version = "0.1.0.dev1"
description = "GitHub repository storage adapter plugin for Peagen"
license = "Apache-2.0"
readme = "README.md"
requires-python = ">=3.10,<3.13"
authors = [{ name = "Jacob Stewart", email = "jacob@swarmauri.com" }]
classifiers = [
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
dependencies = [
    "peagen",
    "PyGithub",
]

[project.entry-points."peagen.storage_adapters"]
github = "peagen_storage_github.github_storage_adapter:GithubStorageAdapter"

[tool.uv.sources]
peagen = { workspace = true }

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
