[package]
name = "swarmauri_crypto_rust"
version = "0.1.0"
edition = "2021"
description = "Rust-based cryptography implementation for Swarmauri"
license = "Apache-2.0"
authors = ["Swarmauri <opensource@swarmauri.com>"]

[lib]
name = "_rust_crypto"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.20", features = ["extension-module"] }
ring = "0.17"
rand = "0.8"
base64 = "0.22"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"

[profile.release]
lto = "thin"
codegen-units = 1
panic = "abort"
strip = "symbols"

[profile.dev]
debug = true
opt-level = 0
