"""Typed JSON-RPC protocol primitives and method registry."""

from .envelope import Error, Request, Response, parse_request
from .error_codes import Code
from . import _registry
from .methods import (
    TASK_SUBMIT,
    KEYS_UPLOAD,
    KEYS_FETCH,
    KEYS_DELETE,
    SECRETS_ADD,
    SECRETS_GET,
    SECRETS_DELETE,
    TASK_CANCEL,
    TASK_PAUSE,
    TASK_RESUME,
    TASK_RETRY,
    TASK_RETRY_FROM,
    TASK_PATCH,
    TASK_GET,
    GUARD_SET,
    WORKER_REGISTER,
    WORKER_HEARTBEAT,
    WORKER_LIST,
    WORK_FINISHED,
    WORK_START,
    WORK_CANCEL,
    POOL_CREATE,
    POOL_JOIN,
    POOL_LIST_TASKS,
)

__all__ = [
    "Error",
    "Request",
    "Response",
    "parse_request",
    "Code",
    "_registry",
    "TASK_SUBMIT",
    "KEYS_UPLOAD",
    "KEYS_FETCH",
    "KEYS_DELETE",
    "SECRETS_ADD",
    "SECRETS_GET",
    "SECRETS_DELETE",
    "TASK_CANCEL",
    "TASK_PAUSE",
    "TASK_RESUME",
    "TASK_RETRY",
    "TASK_RETRY_FROM",
    "TASK_PATCH",
    "TASK_GET",
    "GUARD_SET",
    "WORKER_REGISTER",
    "WORKER_HEARTBEAT",
    "WORKER_LIST",
    "WORK_FINISHED",
    "WORK_START",
    "WORK_CANCEL",
    "POOL_CREATE",
    "POOL_JOIN",
    "POOL_LIST_TASKS",
]
