from __future__ import annotations
from typing import Protocol, Iterable, Mapping
from .spec import Remote

class IRemoteRegistry(Protocol):
    def register(self, remote: Remote) -> None: ...
    def register_many(self, remotes: Iterable[Remote]) -> None: ...
    def get(self, id: str) -> Remote: ...
    def try_get(self, id: str) -> Remote | None: ...
    def remove(self, id: str) -> None: ...
    def all(self) -> Iterable[Remote]: ...
    def to_dict(self) -> dict[str, dict]: ...
    def update_from_dict(self, data: Mapping[str, Mapping]) -> None: ...

class IImportMapBuilder(Protocol):
    def build(self, registry: IRemoteRegistry, *, extra_imports: dict[str,str] | None = None,
              scopes: dict[str, dict[str,str]] | None = None) -> dict: ...
