from __future__ import annotations
from typing import Protocol, Iterable, Mapping, Any, Optional
from .spec import ComponentSpec

class IComponentRegistry(Protocol):
    """Protocol for storing and resolving ComponentSpec entries by role."""
    def register(self, spec: ComponentSpec) -> None: ...
    def register_many(self, specs: Iterable[ComponentSpec]) -> None: ...
    def override(self, role: str, **fields: Any) -> ComponentSpec: ...
    def get(self, role: str) -> ComponentSpec: ...
    def try_get(self, role: str) -> Optional[ComponentSpec]: ...
    def has(self, role: str) -> bool: ...
    def list(self) -> Iterable[ComponentSpec]: ...
    def resolve_props(self, role: str, overrides: Mapping[str, Any] | None = None) -> dict: ...
    def to_dict(self) -> dict[str, dict]: ...
    def update_from_dict(self, data: Mapping[str, Mapping[str, Any]]) -> None: ...
