site_name: ZDX
repo_name: zdx
repo_url: https://github.com/swarmauri/swarmauri-sdk/community/zdx
theme:
  name: material
plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            extensions:
              - griffe_typingdoc
  - search
  - gen-files:
      scripts:
        - docs/_gen_readmes.py
  - literate-nav:
      nav_file: SUMMARY.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - footnotes
  - attr_list
  - def_list
  - tables
