import {
  computed,
  createApp,
  defineComponent,
  onMounted,
  reactive,
} from "https://unpkg.com/vue@3/dist/vue.esm-browser.js";

import { atomRenderers } from "./atoms.js";

function computeGridPlacement(frame, grid, viewport) {
  if (!grid || !frame) {
    return {};
  }

  const columnCount = grid.columns?.length ?? 1;
  const totalGap = grid.gap_x * Math.max(columnCount - 1, 0);
  const averageColumnWidth =
    columnCount > 0
      ? (viewport.width - totalGap) / columnCount
      : viewport.width;
  const stepX = averageColumnWidth + grid.gap_x;
  const stepY = grid.row_height + grid.gap_y;

  const columnStart = Math.round(frame.x / stepX) + 1;
  const rowStart = Math.round(frame.y / stepY) + 1;
  const columnSpan = Math.max(
    1,
    Math.min(
      columnCount,
      Math.round(frame.w / stepX) || 1,
      columnCount - columnStart + 1,
    ),
  );
  const rowSpan = Math.max(1, Math.round(frame.h / grid.row_height) || 1);

  return {
    gridColumn: `${columnStart} / span ${columnSpan}`,
    gridRow: `${rowStart} / span ${rowSpan}`,
  };
}

function resolveManifestUrl() {
  if (window.__LE_MANIFEST_URL__) {
    return window.__LE_MANIFEST_URL__;
  }
  return new URL("manifest.json", window.location.href).toString();
}

const TileHost = defineComponent({
  name: "TileHost",
  props: {
    tile: { type: Object, required: true },
    grid: { type: Object, required: true },
    viewport: { type: Object, required: true },
  },
  setup(props) {
    const renderer = computed(
      () => atomRenderers[props.tile.role] ?? atomRenderers.default,
    );

    const placement = computed(() =>
      computeGridPlacement(props.tile.frame, props.grid, props.viewport),
    );

    return {
      renderer,
      placement,
    };
  },
  template: `
    <div class="tile" :style="placement">
      <component :is="renderer" :tile="tile" />
    </div>
  `,
});

const DashboardApp = defineComponent({
  name: "DashboardApp",
  components: { TileHost },
  setup() {
    const state = reactive({
      manifest: null,
      loading: true,
      error: null,
    });

    async function fetchManifest() {
      try {
        const response = await fetch(resolveManifestUrl());
        if (!response.ok) {
          throw new Error(`Failed to load manifest: ${response.statusText}`);
        }

        state.manifest = await response.json();
      } catch (err) {
        state.error = err;
      } finally {
        state.loading = false;
      }
    }

    onMounted(fetchManifest);

    const gridStyle = computed(() => {
      if (!state.manifest) {
        return {};
      }

      const grid = state.manifest.grid;
      const columnCount = grid.columns?.length ?? 1;
      return {
        gridTemplateColumns: `repeat(${columnCount}, minmax(200px, 1fr))`,
        gap: `${grid.gap_y}px ${grid.gap_x}px`,
      };
    });

    const summary = computed(() => {
      if (!state.manifest) {
        return { tileCount: 0, roleCount: 0 };
      }
      const tiles = state.manifest.tiles ?? [];
      const roles = new Set(tiles.map((tile) => tile.role));
      return { tileCount: tiles.length, roleCount: roles.size };
    });

    return {
      state,
      gridStyle,
      summary,
    };
  },
  template: `
    <div class="dashboard">
      <header class="dashboard__header">
        <div>
          <h1 class="dashboard__title">Revenue Operations Overview</h1>
          <p class="dashboard__meta">
            <span>Manifest v{{ state.manifest?.version ?? "—" }}</span>
            <span aria-hidden="true">•</span>
            <span>Tiles: {{ summary.tileCount }}</span>
            <span aria-hidden="true">•</span>
            <span>Roles: {{ summary.roleCount }}</span>
          </p>
        </div>
        <div class="dashboard__meta">
          <span>Viewport: {{ state.manifest?.viewport?.width ?? "—" }}×{{ state.manifest?.viewport?.height ?? "—" }}</span>
          <span aria-hidden="true">•</span>
          <span>Generated by layout-engine</span>
        </div>
      </header>

      <div v-if="state.loading" class="dashboard__meta">Fetching manifest…</div>
      <div v-else-if="state.error" class="dashboard__meta">
        Failed to load manifest: {{ state.error.message }}
      </div>

      <section
        v-if="state.manifest && !state.error"
        class="dashboard-grid"
        :style="gridStyle"
      >
        <TileHost
          v-for="tile in state.manifest.tiles"
          :key="tile.id"
          :tile="tile"
          :grid="state.manifest.grid"
          :viewport="state.manifest.viewport"
        />
      </section>
    </div>
  `,
});

createApp(DashboardApp).mount("#app");
