services:
  mkdocs:
    image: python:3.12-slim
    container_name: mkdocs
    # restart: unless-stopped
    ports:
      - "8000:8000" # Expose mkdocs on port 8000
    volumes:
      - ../../docs:/docs # Mount the repo docs directory
      - ../../pkgs:/pkgs # Mount the repo pkgs directory
    working_dir: /docs
    command: |
      sh -c "
        set -euo pipefail

        # Use an ephemeral virtualenv inside the container
        export UV_PROJECT_ENVIRONMENT=/tmp/.venv

        # Install uv and sync docs project dependencies
        pip install --no-cache-dir -U pip uv && 
        uv sync &&

        # Generate API docs (incremental)
        uv run python scripts/gen_api.py --manifest api_manifest.yaml --changed-only &&

        # Serve the static site
        uv run mkdocs serve -a 0.0.0.0:8000
      "
    networks:
      - dockernet

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    # restart: unless-stopped
    depends_on:
      - mkdocs
    ports:
      - "80:80"   # HTTP
      - "443:443" # HTTPS
      - "81:81"   # Admin UI
    volumes:
      - ./npm/data:/data
      - ./npm/letsencrypt:/etc/letsencrypt
    environment:
      DISABLE_IPV6: "true"
    networks:
      - dockernet

# Define networks at the bottom of the file
networks:
  dockernet:
    driver: bridge

