from __future__ import annotations

EXPECTED_METADATA = {
    "application_fee": {
        "columns": [
            "stripe_application_fee_id",
            "amount",
            "currency",
            "originating_payment_intent_id",
            "connected_account_id",
            "refunded",
            "metadata_",
        ],
        "foreign_keys": [
            ["originating_payment_intent_id", "'payment_intents.id'"],
            ["connected_account_id", "'connected_accounts.id'"],
        ],
        "requests": {
            "create": [
                "amount",
                "connected_account_id",
                "currency",
                "metadata_",
                "originating_payment_intent_id",
                "refunded",
                "stripe_application_fee_id",
            ],
            "merge": [
                "amount",
                "connected_account_id",
                "currency",
                "metadata_",
                "originating_payment_intent_id",
                "refunded",
                "stripe_application_fee_id",
            ],
            "replace": [
                "amount",
                "connected_account_id",
                "currency",
                "metadata_",
                "originating_payment_intent_id",
                "refunded",
                "stripe_application_fee_id",
            ],
            "update": [
                "amount",
                "connected_account_id",
                "currency",
                "metadata_",
                "originating_payment_intent_id",
                "refunded",
                "stripe_application_fee_id",
            ],
        },
        "responses": {
            "list": [
                "amount",
                "connected_account_id",
                "currency",
                "metadata_",
                "originating_payment_intent_id",
                "refunded",
                "stripe_application_fee_id",
            ],
            "read": [
                "amount",
                "connected_account_id",
                "currency",
                "metadata_",
                "originating_payment_intent_id",
                "refunded",
                "stripe_application_fee_id",
            ],
        },
    },
    "balance_top_off": {
        "columns": [
            "balance_id",
            "amount",
            "currency",
            "trigger",
            "method",
            "status",
            "stripe_payment_intent_id",
            "processed_at",
            "metadata_",
        ],
        "foreign_keys": [],
        "requests": {
            "create": [
                "amount",
                "balance_id",
                "currency",
                "metadata_",
                "method",
                "processed_at",
                "status",
                "stripe_payment_intent_id",
                "trigger",
            ],
            "replace": [
                "amount",
                "balance_id",
                "currency",
                "metadata_",
                "method",
                "processed_at",
                "status",
                "stripe_payment_intent_id",
                "trigger",
            ],
            "update": [
                "amount",
                "balance_id",
                "currency",
                "metadata_",
                "method",
                "processed_at",
                "status",
                "stripe_payment_intent_id",
                "trigger",
            ],
        },
        "responses": {
            "list": [
                "amount",
                "balance_id",
                "currency",
                "metadata_",
                "method",
                "processed_at",
                "status",
                "stripe_payment_intent_id",
                "trigger",
            ],
            "read": [
                "amount",
                "balance_id",
                "currency",
                "metadata_",
                "method",
                "processed_at",
                "status",
                "stripe_payment_intent_id",
                "trigger",
            ],
        },
    },
    "checkout_session": {
        "columns": [
            "stripe_checkout_session_id",
            "mode",
            "customer_id",
            "status",
            "success_url",
            "cancel_url",
            "line_items",
            "connected_account_id",
            "completed_at",
            "metadata_",
        ],
        "foreign_keys": [
            ["customer_id", "'customers.id'"],
            ["connected_account_id", "'connected_accounts.id'"],
        ],
        "requests": {
            "create": [
                "cancel_url",
                "completed_at",
                "connected_account_id",
                "customer_id",
                "line_items",
                "metadata_",
                "mode",
                "status",
                "stripe_checkout_session_id",
                "success_url",
            ],
            "merge": [
                "cancel_url",
                "completed_at",
                "connected_account_id",
                "customer_id",
                "line_items",
                "metadata_",
                "mode",
                "status",
                "stripe_checkout_session_id",
                "success_url",
            ],
            "replace": [
                "cancel_url",
                "completed_at",
                "connected_account_id",
                "customer_id",
                "line_items",
                "metadata_",
                "mode",
                "status",
                "stripe_checkout_session_id",
                "success_url",
            ],
            "update": [
                "cancel_url",
                "completed_at",
                "connected_account_id",
                "customer_id",
                "line_items",
                "metadata_",
                "mode",
                "status",
                "stripe_checkout_session_id",
                "success_url",
            ],
        },
        "responses": {
            "list": [
                "cancel_url",
                "completed_at",
                "connected_account_id",
                "customer_id",
                "line_items",
                "metadata_",
                "mode",
                "status",
                "stripe_checkout_session_id",
                "success_url",
            ],
            "read": [
                "cancel_url",
                "completed_at",
                "connected_account_id",
                "customer_id",
                "line_items",
                "metadata_",
                "mode",
                "status",
                "stripe_checkout_session_id",
                "success_url",
            ],
        },
    },
    "connected_account": {
        "columns": [
            "stripe_account_id",
            "type",
            "payouts_enabled",
            "charges_enabled",
            "capabilities",
            "metadata_",
        ],
        "foreign_keys": [],
        "requests": {
            "create": [
                "capabilities",
                "charges_enabled",
                "metadata_",
                "payouts_enabled",
                "stripe_account_id",
                "type",
            ],
            "merge": [
                "capabilities",
                "charges_enabled",
                "metadata_",
                "payouts_enabled",
                "stripe_account_id",
                "type",
            ],
            "replace": [
                "capabilities",
                "charges_enabled",
                "metadata_",
                "payouts_enabled",
                "stripe_account_id",
                "type",
            ],
            "update": [
                "capabilities",
                "charges_enabled",
                "metadata_",
                "payouts_enabled",
                "stripe_account_id",
                "type",
            ],
        },
        "responses": {
            "list": [
                "capabilities",
                "charges_enabled",
                "metadata_",
                "payouts_enabled",
                "stripe_account_id",
                "type",
            ],
            "read": [
                "capabilities",
                "charges_enabled",
                "metadata_",
                "payouts_enabled",
                "stripe_account_id",
                "type",
            ],
        },
    },
    "credit_grant": {
        "columns": [
            "customer_id",
            "currency",
            "total_amount",
            "remaining_amount",
            "grant_type",
            "starts_at",
            "expires_at",
            "status",
            "metadata_",
        ],
        "foreign_keys": [],
        "requests": {
            "create": [
                "currency",
                "customer_id",
                "expires_at",
                "grant_type",
                "metadata_",
                "starts_at",
                "status",
                "total_amount",
            ],
            "merge": [
                "currency",
                "customer_id",
                "expires_at",
                "grant_type",
                "metadata_",
                "remaining_amount",
                "starts_at",
                "status",
                "total_amount",
            ],
            "replace": [
                "currency",
                "customer_id",
                "expires_at",
                "grant_type",
                "metadata_",
                "remaining_amount",
                "starts_at",
                "status",
                "total_amount",
            ],
            "update": [
                "currency",
                "customer_id",
                "expires_at",
                "grant_type",
                "metadata_",
                "remaining_amount",
                "starts_at",
                "status",
                "total_amount",
            ],
        },
        "responses": {
            "list": [
                "currency",
                "customer_id",
                "expires_at",
                "grant_type",
                "metadata_",
                "remaining_amount",
                "starts_at",
                "status",
                "total_amount",
            ],
            "read": [
                "currency",
                "customer_id",
                "expires_at",
                "grant_type",
                "metadata_",
                "remaining_amount",
                "starts_at",
                "status",
                "total_amount",
            ],
        },
    },
    "credit_ledger": {
        "columns": [
            "customer_id",
            "currency",
            "direction",
            "delta",
            "balance_id",
            "grant_id",
            "usage_event_id",
            "subject_ref",
            "processed_at",
            "metadata_",
        ],
        "foreign_keys": [],
        "requests": {
            "create": [
                "balance_id",
                "currency",
                "customer_id",
                "delta",
                "direction",
                "grant_id",
                "metadata_",
                "processed_at",
                "subject_ref",
                "usage_event_id",
            ],
            "replace": [
                "balance_id",
                "currency",
                "customer_id",
                "delta",
                "direction",
                "grant_id",
                "metadata_",
                "processed_at",
                "subject_ref",
                "usage_event_id",
            ],
            "update": [
                "balance_id",
                "currency",
                "customer_id",
                "delta",
                "direction",
                "grant_id",
                "metadata_",
                "processed_at",
                "subject_ref",
                "usage_event_id",
            ],
        },
        "responses": {
            "list": [
                "balance_id",
                "currency",
                "customer_id",
                "delta",
                "direction",
                "grant_id",
                "metadata_",
                "processed_at",
                "subject_ref",
                "usage_event_id",
            ],
            "read": [
                "balance_id",
                "currency",
                "customer_id",
                "delta",
                "direction",
                "grant_id",
                "metadata_",
                "processed_at",
                "subject_ref",
                "usage_event_id",
            ],
        },
    },
    "credit_usage_policy": {
        "columns": ["feature_key", "credits_per_unit", "min_granularity", "metadata_"],
        "foreign_keys": [],
        "requests": {
            "create": [
                "credits_per_unit",
                "feature_key",
                "metadata_",
                "min_granularity",
            ],
            "merge": [
                "credits_per_unit",
                "feature_key",
                "metadata_",
                "min_granularity",
            ],
            "replace": [
                "credits_per_unit",
                "feature_key",
                "metadata_",
                "min_granularity",
            ],
            "update": [
                "credits_per_unit",
                "feature_key",
                "metadata_",
                "min_granularity",
            ],
        },
        "responses": {
            "list": ["credits_per_unit", "feature_key", "metadata_", "min_granularity"],
            "read": ["credits_per_unit", "feature_key", "metadata_", "min_granularity"],
        },
    },
    "customer": {
        "columns": [
            "stripe_customer_id",
            "email",
            "name",
            "default_payment_method_ref",
            "tax_exempt",
            "active",
            "metadata_",
        ],
        "foreign_keys": [],
        "requests": {
            "create": [
                "active",
                "default_payment_method_ref",
                "email",
                "metadata_",
                "name",
                "stripe_customer_id",
                "tax_exempt",
            ],
            "merge": [
                "active",
                "default_payment_method_ref",
                "email",
                "metadata_",
                "name",
                "stripe_customer_id",
                "tax_exempt",
            ],
            "replace": [
                "active",
                "default_payment_method_ref",
                "email",
                "metadata_",
                "name",
                "stripe_customer_id",
                "tax_exempt",
            ],
            "update": [
                "active",
                "default_payment_method_ref",
                "email",
                "metadata_",
                "name",
                "stripe_customer_id",
                "tax_exempt",
            ],
        },
        "responses": {
            "list": [
                "active",
                "default_payment_method_ref",
                "email",
                "metadata_",
                "name",
                "stripe_customer_id",
                "tax_exempt",
            ],
            "read": [
                "active",
                "default_payment_method_ref",
                "email",
                "metadata_",
                "name",
                "stripe_customer_id",
                "tax_exempt",
            ],
        },
    },
    "customer_account_link": {
        "columns": ["customer_id", "connected_account_id", "role", "metadata_"],
        "foreign_keys": [
            ["customer_id", "'customers.id'"],
            ["connected_account_id", "'connected_accounts.id'"],
        ],
        "requests": {
            "create": ["connected_account_id", "customer_id", "metadata_", "role"],
            "merge": ["connected_account_id", "customer_id", "metadata_", "role"],
            "replace": ["connected_account_id", "customer_id", "metadata_", "role"],
            "update": ["connected_account_id", "customer_id", "metadata_", "role"],
        },
        "responses": {
            "list": ["connected_account_id", "customer_id", "metadata_", "role"],
            "read": ["connected_account_id", "customer_id", "metadata_", "role"],
        },
    },
    "customer_balance": {
        "columns": [
            "customer_id",
            "currency",
            "available_amount",
            "pending_amount",
            "hold_amount",
            "auto_top_off_enabled",
            "top_off_mode",
            "top_off_threshold",
            "top_off_amount",
            "stripe_customer_id",
            "metadata_",
        ],
        "foreign_keys": [],
        "requests": {
            "create": [
                "auto_top_off_enabled",
                "available_amount",
                "currency",
                "customer_id",
                "hold_amount",
                "metadata_",
                "pending_amount",
                "stripe_customer_id",
                "top_off_amount",
                "top_off_mode",
                "top_off_threshold",
            ],
            "merge": [
                "auto_top_off_enabled",
                "available_amount",
                "currency",
                "customer_id",
                "hold_amount",
                "metadata_",
                "pending_amount",
                "stripe_customer_id",
                "top_off_amount",
                "top_off_mode",
                "top_off_threshold",
            ],
            "replace": [
                "auto_top_off_enabled",
                "available_amount",
                "currency",
                "customer_id",
                "hold_amount",
                "metadata_",
                "pending_amount",
                "stripe_customer_id",
                "top_off_amount",
                "top_off_mode",
                "top_off_threshold",
            ],
            "update": [
                "auto_top_off_enabled",
                "available_amount",
                "currency",
                "customer_id",
                "hold_amount",
                "metadata_",
                "pending_amount",
                "stripe_customer_id",
                "top_off_amount",
                "top_off_mode",
                "top_off_threshold",
            ],
        },
        "responses": {
            "list": [
                "auto_top_off_enabled",
                "available_amount",
                "currency",
                "customer_id",
                "hold_amount",
                "metadata_",
                "pending_amount",
                "stripe_customer_id",
                "top_off_amount",
                "top_off_mode",
                "top_off_threshold",
            ],
            "read": [
                "auto_top_off_enabled",
                "available_amount",
                "currency",
                "customer_id",
                "hold_amount",
                "metadata_",
                "pending_amount",
                "stripe_customer_id",
                "top_off_amount",
                "top_off_mode",
                "top_off_threshold",
            ],
        },
    },
    "feature": {
        "columns": [
            "key",
            "name",
            "description",
            "metering",
            "unit_label",
            "metadata_",
        ],
        "foreign_keys": [],
        "requests": {
            "create": [
                "description",
                "key",
                "metadata_",
                "metering",
                "name",
                "unit_label",
            ],
            "replace": [
                "description",
                "key",
                "metadata_",
                "metering",
                "name",
                "unit_label",
            ],
            "update": [
                "description",
                "key",
                "metadata_",
                "metering",
                "name",
                "unit_label",
            ],
        },
        "responses": {
            "list": [
                "description",
                "key",
                "metadata_",
                "metering",
                "name",
                "unit_label",
            ],
            "read": [
                "description",
                "key",
                "metadata_",
                "metering",
                "name",
                "unit_label",
            ],
        },
    },
    "invoice": {
        "columns": [
            "stripe_invoice_id",
            "customer_id",
            "subscription_id",
            "status",
            "number",
            "currency",
            "total",
            "amount_due",
            "amount_paid",
            "amount_remaining",
            "due_date",
            "hosted_invoice_url",
            "collection_method",
            "metadata_",
        ],
        "foreign_keys": [
            ["customer_id", "'customers.id'"],
            ["subscription_id", "'subscriptions.id'"],
        ],
        "requests": {
            "create": [
                "amount_due",
                "amount_paid",
                "amount_remaining",
                "collection_method",
                "currency",
                "customer_id",
                "due_date",
                "hosted_invoice_url",
                "metadata_",
                "number",
                "status",
                "stripe_invoice_id",
                "subscription_id",
                "total",
            ],
            "merge": [
                "amount_due",
                "amount_paid",
                "amount_remaining",
                "collection_method",
                "currency",
                "customer_id",
                "due_date",
                "hosted_invoice_url",
                "metadata_",
                "number",
                "status",
                "stripe_invoice_id",
                "subscription_id",
                "total",
            ],
            "replace": [
                "amount_due",
                "amount_paid",
                "amount_remaining",
                "collection_method",
                "currency",
                "customer_id",
                "due_date",
                "hosted_invoice_url",
                "metadata_",
                "number",
                "status",
                "stripe_invoice_id",
                "subscription_id",
                "total",
            ],
            "update": [
                "amount_due",
                "amount_paid",
                "amount_remaining",
                "collection_method",
                "currency",
                "customer_id",
                "due_date",
                "hosted_invoice_url",
                "metadata_",
                "number",
                "status",
                "stripe_invoice_id",
                "subscription_id",
                "total",
            ],
        },
        "responses": {
            "list": [
                "amount_due",
                "amount_paid",
                "amount_remaining",
                "collection_method",
                "currency",
                "customer_id",
                "due_date",
                "hosted_invoice_url",
                "metadata_",
                "number",
                "status",
                "stripe_invoice_id",
                "subscription_id",
                "total",
            ],
            "read": [
                "amount_due",
                "amount_paid",
                "amount_remaining",
                "collection_method",
                "currency",
                "customer_id",
                "due_date",
                "hosted_invoice_url",
                "metadata_",
                "number",
                "status",
                "stripe_invoice_id",
                "subscription_id",
                "total",
            ],
        },
    },
    "invoice_line_item": {
        "columns": [
            "invoice_id",
            "subscription_item_id",
            "price_id",
            "description",
            "quantity",
            "unit_amount",
            "amount",
            "proration",
            "tax_details",
            "metadata_",
        ],
        "foreign_keys": [
            ["invoice_id", "'invoices.id'"],
            ["subscription_item_id", "'subscription_items.id'"],
            ["price_id", "'prices.id'"],
        ],
        "requests": {
            "create": [
                "amount",
                "description",
                "invoice_id",
                "metadata_",
                "price_id",
                "proration",
                "quantity",
                "subscription_item_id",
                "tax_details",
                "unit_amount",
            ],
            "merge": [
                "amount",
                "description",
                "invoice_id",
                "metadata_",
                "price_id",
                "proration",
                "quantity",
                "subscription_item_id",
                "tax_details",
                "unit_amount",
            ],
            "replace": [
                "amount",
                "description",
                "invoice_id",
                "metadata_",
                "price_id",
                "proration",
                "quantity",
                "subscription_item_id",
                "tax_details",
                "unit_amount",
            ],
            "update": [
                "amount",
                "description",
                "invoice_id",
                "metadata_",
                "price_id",
                "proration",
                "quantity",
                "subscription_item_id",
                "tax_details",
                "unit_amount",
            ],
        },
        "responses": {
            "list": [
                "amount",
                "description",
                "invoice_id",
                "metadata_",
                "price_id",
                "proration",
                "quantity",
                "subscription_item_id",
                "tax_details",
                "unit_amount",
            ],
            "read": [
                "amount",
                "description",
                "invoice_id",
                "metadata_",
                "price_id",
                "proration",
                "quantity",
                "subscription_item_id",
                "tax_details",
                "unit_amount",
            ],
        },
    },
    "payment_intent": {
        "columns": [
            "stripe_payment_intent_id",
            "customer_id",
            "currency",
            "amount",
            "status",
            "capture_method",
            "payment_method_types",
            "connected_account_id",
            "application_fee_amount",
            "transfer_data",
            "metadata_",
        ],
        "foreign_keys": [
            ["customer_id", "'customers.id'"],
            ["connected_account_id", "'connected_accounts.id'"],
        ],
        "requests": {
            "create": [
                "amount",
                "application_fee_amount",
                "capture_method",
                "connected_account_id",
                "currency",
                "customer_id",
                "metadata_",
                "payment_method_types",
                "status",
                "stripe_payment_intent_id",
                "transfer_data",
            ],
            "merge": [
                "amount",
                "application_fee_amount",
                "capture_method",
                "connected_account_id",
                "currency",
                "customer_id",
                "metadata_",
                "payment_method_types",
                "status",
                "stripe_payment_intent_id",
                "transfer_data",
            ],
            "replace": [
                "amount",
                "application_fee_amount",
                "capture_method",
                "connected_account_id",
                "currency",
                "customer_id",
                "metadata_",
                "payment_method_types",
                "status",
                "stripe_payment_intent_id",
                "transfer_data",
            ],
            "update": [
                "amount",
                "application_fee_amount",
                "capture_method",
                "connected_account_id",
                "currency",
                "customer_id",
                "metadata_",
                "payment_method_types",
                "status",
                "stripe_payment_intent_id",
                "transfer_data",
            ],
        },
        "responses": {
            "list": [
                "amount",
                "application_fee_amount",
                "capture_method",
                "connected_account_id",
                "currency",
                "customer_id",
                "metadata_",
                "payment_method_types",
                "status",
                "stripe_payment_intent_id",
                "transfer_data",
            ],
            "read": [
                "amount",
                "application_fee_amount",
                "capture_method",
                "connected_account_id",
                "currency",
                "customer_id",
                "metadata_",
                "payment_method_types",
                "status",
                "stripe_payment_intent_id",
                "transfer_data",
            ],
        },
    },
    "price": {
        "columns": [
            "stripe_price_id",
            "product_id",
            "currency",
            "billing_scheme",
            "unit_amount",
            "recurring_interval",
            "recurring_count",
            "usage_type",
            "aggregate_usage",
            "transform_quantity",
            "tax_behavior",
            "nickname",
            "metadata_",
        ],
        "foreign_keys": [
            ["product_id", "lambda cls: f'{_infer_schema(cls)}.billing_products.id'"]
        ],
        "requests": {
            "create": [
                "aggregate_usage",
                "billing_scheme",
                "currency",
                "metadata_",
                "nickname",
                "product_id",
                "recurring_count",
                "recurring_interval",
                "stripe_price_id",
                "tax_behavior",
                "transform_quantity",
                "unit_amount",
                "usage_type",
            ],
            "replace": [
                "aggregate_usage",
                "billing_scheme",
                "currency",
                "metadata_",
                "nickname",
                "product_id",
                "recurring_count",
                "recurring_interval",
                "tax_behavior",
                "transform_quantity",
                "unit_amount",
                "usage_type",
            ],
            "update": [
                "aggregate_usage",
                "billing_scheme",
                "currency",
                "metadata_",
                "nickname",
                "product_id",
                "recurring_count",
                "recurring_interval",
                "tax_behavior",
                "transform_quantity",
                "unit_amount",
                "usage_type",
            ],
        },
        "responses": {
            "list": [
                "aggregate_usage",
                "billing_scheme",
                "currency",
                "metadata_",
                "nickname",
                "product_id",
                "recurring_count",
                "recurring_interval",
                "stripe_price_id",
                "tax_behavior",
                "transform_quantity",
                "unit_amount",
                "usage_type",
            ],
            "read": [
                "aggregate_usage",
                "billing_scheme",
                "currency",
                "metadata_",
                "nickname",
                "product_id",
                "recurring_count",
                "recurring_interval",
                "stripe_price_id",
                "tax_behavior",
                "transform_quantity",
                "unit_amount",
                "usage_type",
            ],
        },
    },
    "price_feature_entitlement": {
        "columns": [
            "price_id",
            "feature_id",
            "limit_per_period",
            "overage_unit_amount",
            "period",
            "metering_window",
        ],
        "foreign_keys": [
            ["price_id", "lambda cls: f'{_infer_schema(cls)}.billing_prices.id'"],
            ["feature_id", "lambda cls: f'{_infer_schema(cls)}.billing_features.id'"],
        ],
        "requests": {
            "create": [
                "feature_id",
                "limit_per_period",
                "metering_window",
                "overage_unit_amount",
                "period",
                "price_id",
            ],
            "replace": [
                "feature_id",
                "limit_per_period",
                "metering_window",
                "overage_unit_amount",
                "period",
                "price_id",
            ],
            "update": [
                "feature_id",
                "limit_per_period",
                "metering_window",
                "overage_unit_amount",
                "period",
                "price_id",
            ],
        },
        "responses": {
            "list": [
                "feature_id",
                "limit_per_period",
                "metering_window",
                "overage_unit_amount",
                "period",
                "price_id",
            ],
            "read": [
                "feature_id",
                "limit_per_period",
                "metering_window",
                "overage_unit_amount",
                "period",
                "price_id",
            ],
        },
    },
    "price_tier": {
        "columns": ["price_id", "up_to", "flat_amount", "unit_amount"],
        "foreign_keys": [
            ["price_id", "lambda cls: f'{_infer_schema(cls)}.billing_prices.id'"]
        ],
        "requests": {
            "create": ["flat_amount", "price_id", "unit_amount", "up_to"],
            "replace": ["flat_amount", "price_id", "unit_amount", "up_to"],
            "update": ["flat_amount", "price_id", "unit_amount", "up_to"],
        },
        "responses": {
            "list": ["flat_amount", "price_id", "unit_amount", "up_to"],
            "read": ["flat_amount", "price_id", "unit_amount", "up_to"],
        },
    },
    "product": {
        "columns": ["stripe_product_id", "name", "description", "metadata_"],
        "foreign_keys": [],
        "requests": {
            "create": ["description", "metadata_", "name", "stripe_product_id"],
            "replace": ["description", "metadata_", "name"],
            "update": ["description", "metadata_", "name"],
        },
        "responses": {
            "list": ["description", "metadata_", "name", "stripe_product_id"],
            "read": ["description", "metadata_", "name", "stripe_product_id"],
        },
    },
    "refund": {
        "columns": [
            "stripe_refund_id",
            "payment_intent_id",
            "amount",
            "status",
            "reason",
            "metadata_",
        ],
        "foreign_keys": [["payment_intent_id", "'payment_intents.id'"]],
        "requests": {
            "create": [
                "amount",
                "metadata_",
                "payment_intent_id",
                "reason",
                "status",
                "stripe_refund_id",
            ],
            "merge": [
                "amount",
                "metadata_",
                "payment_intent_id",
                "reason",
                "status",
                "stripe_refund_id",
            ],
            "replace": [
                "amount",
                "metadata_",
                "payment_intent_id",
                "reason",
                "status",
                "stripe_refund_id",
            ],
            "update": [
                "amount",
                "metadata_",
                "payment_intent_id",
                "reason",
                "status",
                "stripe_refund_id",
            ],
        },
        "responses": {
            "list": [
                "amount",
                "metadata_",
                "payment_intent_id",
                "reason",
                "status",
                "stripe_refund_id",
            ],
            "read": [
                "amount",
                "metadata_",
                "payment_intent_id",
                "reason",
                "status",
                "stripe_refund_id",
            ],
        },
    },
    "seat_allocation": {
        "columns": [
            "subscription_item_id",
            "subject_ref",
            "role",
            "state",
            "assigned_at",
            "released_at",
        ],
        "foreign_keys": [["subscription_item_id", "'subscription_items.id'"]],
        "requests": {
            "create": [
                "assigned_at",
                "released_at",
                "role",
                "state",
                "subject_ref",
                "subscription_item_id",
            ],
            "merge": [
                "assigned_at",
                "released_at",
                "role",
                "state",
                "subject_ref",
                "subscription_item_id",
            ],
            "replace": [
                "assigned_at",
                "released_at",
                "role",
                "state",
                "subject_ref",
                "subscription_item_id",
            ],
            "update": [
                "assigned_at",
                "released_at",
                "role",
                "state",
                "subject_ref",
                "subscription_item_id",
            ],
        },
        "responses": {
            "list": [
                "assigned_at",
                "released_at",
                "role",
                "state",
                "subject_ref",
                "subscription_item_id",
            ],
            "read": [
                "assigned_at",
                "released_at",
                "role",
                "state",
                "subject_ref",
                "subscription_item_id",
            ],
        },
    },
    "split_rule": {
        "columns": [
            "key",
            "mode",
            "application_fee_bps",
            "fixed_application_fee_amount",
            "transfer_dest_account_id",
            "metadata_",
        ],
        "foreign_keys": [["transfer_dest_account_id", "'connected_accounts.id'"]],
        "requests": {
            "create": [
                "application_fee_bps",
                "fixed_application_fee_amount",
                "key",
                "metadata_",
                "mode",
                "transfer_dest_account_id",
            ],
            "merge": [
                "application_fee_bps",
                "fixed_application_fee_amount",
                "key",
                "metadata_",
                "mode",
                "transfer_dest_account_id",
            ],
            "replace": [
                "application_fee_bps",
                "fixed_application_fee_amount",
                "key",
                "metadata_",
                "mode",
                "transfer_dest_account_id",
            ],
            "update": [
                "application_fee_bps",
                "fixed_application_fee_amount",
                "key",
                "metadata_",
                "mode",
                "transfer_dest_account_id",
            ],
        },
        "responses": {
            "list": [
                "application_fee_bps",
                "fixed_application_fee_amount",
                "key",
                "metadata_",
                "mode",
                "transfer_dest_account_id",
            ],
            "read": [
                "application_fee_bps",
                "fixed_application_fee_amount",
                "key",
                "metadata_",
                "mode",
                "transfer_dest_account_id",
            ],
        },
    },
    "stripe_event_log": {
        "columns": [
            "stripe_event_id",
            "event_type",
            "api_version",
            "event_created_ts",
            "account",
            "payload",
            "status",
            "processed_at",
            "error_message",
            "stripe_request_id",
        ],
        "foreign_keys": [],
        "requests": {
            "create": [
                "account",
                "api_version",
                "error_message",
                "event_created_ts",
                "event_type",
                "payload",
                "processed_at",
                "status",
                "stripe_event_id",
                "stripe_request_id",
            ],
            "merge": [
                "account",
                "api_version",
                "error_message",
                "event_created_ts",
                "event_type",
                "payload",
                "processed_at",
                "status",
                "stripe_event_id",
                "stripe_request_id",
            ],
            "replace": [
                "account",
                "api_version",
                "error_message",
                "event_created_ts",
                "event_type",
                "payload",
                "processed_at",
                "status",
                "stripe_event_id",
                "stripe_request_id",
            ],
            "update": [
                "account",
                "api_version",
                "error_message",
                "event_created_ts",
                "event_type",
                "payload",
                "processed_at",
                "status",
                "stripe_event_id",
                "stripe_request_id",
            ],
        },
        "responses": {
            "list": [
                "account",
                "api_version",
                "error_message",
                "event_created_ts",
                "event_type",
                "payload",
                "processed_at",
                "status",
                "stripe_event_id",
                "stripe_request_id",
            ],
            "read": [
                "account",
                "api_version",
                "error_message",
                "event_created_ts",
                "event_type",
                "payload",
                "processed_at",
                "status",
                "stripe_event_id",
                "stripe_request_id",
            ],
        },
    },
    "subscription": {
        "columns": [
            "stripe_subscription_id",
            "customer_id",
            "status",
            "start_date",
            "cancel_at_period_end",
            "current_period_start",
            "current_period_end",
            "trial_end",
            "collection_method",
            "days_until_due",
            "metadata_",
        ],
        "foreign_keys": [["customer_id", "'customers.id'"]],
        "requests": {
            "create": [
                "cancel_at_period_end",
                "collection_method",
                "current_period_end",
                "current_period_start",
                "customer_id",
                "days_until_due",
                "metadata_",
                "start_date",
                "status",
                "stripe_subscription_id",
                "trial_end",
            ],
            "merge": [
                "cancel_at_period_end",
                "collection_method",
                "current_period_end",
                "current_period_start",
                "customer_id",
                "days_until_due",
                "metadata_",
                "start_date",
                "status",
                "stripe_subscription_id",
                "trial_end",
            ],
            "replace": [
                "cancel_at_period_end",
                "collection_method",
                "current_period_end",
                "current_period_start",
                "customer_id",
                "days_until_due",
                "metadata_",
                "start_date",
                "status",
                "stripe_subscription_id",
                "trial_end",
            ],
            "update": [
                "cancel_at_period_end",
                "collection_method",
                "current_period_end",
                "current_period_start",
                "customer_id",
                "days_until_due",
                "metadata_",
                "start_date",
                "status",
                "stripe_subscription_id",
                "trial_end",
            ],
        },
        "responses": {
            "list": [
                "cancel_at_period_end",
                "collection_method",
                "current_period_end",
                "current_period_start",
                "customer_id",
                "days_until_due",
                "metadata_",
                "start_date",
                "status",
                "stripe_subscription_id",
                "trial_end",
            ],
            "read": [
                "cancel_at_period_end",
                "collection_method",
                "current_period_end",
                "current_period_start",
                "customer_id",
                "days_until_due",
                "metadata_",
                "start_date",
                "status",
                "stripe_subscription_id",
                "trial_end",
            ],
        },
    },
    "subscription_item": {
        "columns": [
            "subscription_id",
            "price_id",
            "stripe_subscription_item_id",
            "quantity",
            "metadata_",
        ],
        "foreign_keys": [
            ["subscription_id", "'subscriptions.id'"],
            ["price_id", "'prices.id'"],
        ],
        "requests": {
            "create": [
                "metadata_",
                "price_id",
                "quantity",
                "stripe_subscription_item_id",
                "subscription_id",
            ],
            "merge": [
                "metadata_",
                "price_id",
                "quantity",
                "stripe_subscription_item_id",
                "subscription_id",
            ],
            "replace": [
                "metadata_",
                "price_id",
                "quantity",
                "stripe_subscription_item_id",
                "subscription_id",
            ],
            "update": [
                "metadata_",
                "price_id",
                "quantity",
                "stripe_subscription_item_id",
                "subscription_id",
            ],
        },
        "responses": {
            "list": [
                "metadata_",
                "price_id",
                "quantity",
                "stripe_subscription_item_id",
                "subscription_id",
            ],
            "read": [
                "metadata_",
                "price_id",
                "quantity",
                "stripe_subscription_item_id",
                "subscription_id",
            ],
        },
    },
    "transfer": {
        "columns": [
            "stripe_transfer_id",
            "payment_intent_id",
            "amount",
            "currency",
            "destination_account_id",
            "reversed",
            "metadata_",
        ],
        "foreign_keys": [
            ["payment_intent_id", "'payment_intents.id'"],
            ["destination_account_id", "'connected_accounts.id'"],
        ],
        "requests": {
            "create": [
                "amount",
                "currency",
                "destination_account_id",
                "metadata_",
                "payment_intent_id",
                "reversed",
                "stripe_transfer_id",
            ],
            "merge": [
                "amount",
                "currency",
                "destination_account_id",
                "metadata_",
                "payment_intent_id",
                "reversed",
                "stripe_transfer_id",
            ],
            "replace": [
                "amount",
                "currency",
                "destination_account_id",
                "metadata_",
                "payment_intent_id",
                "reversed",
                "stripe_transfer_id",
            ],
            "update": [
                "amount",
                "currency",
                "destination_account_id",
                "metadata_",
                "payment_intent_id",
                "reversed",
                "stripe_transfer_id",
            ],
        },
        "responses": {
            "list": [
                "amount",
                "currency",
                "destination_account_id",
                "metadata_",
                "payment_intent_id",
                "reversed",
                "stripe_transfer_id",
            ],
            "read": [
                "amount",
                "currency",
                "destination_account_id",
                "metadata_",
                "payment_intent_id",
                "reversed",
                "stripe_transfer_id",
            ],
        },
    },
    "usage_event": {
        "columns": [
            "subscription_item_id",
            "feature_id",
            "quantity",
            "event_ts",
            "idempotency_key",
            "source",
            "metadata_",
        ],
        "foreign_keys": [
            ["subscription_item_id", "'subscription_items.id'"],
            ["feature_id", "'features.id'"],
        ],
        "requests": {
            "create": [
                "event_ts",
                "feature_id",
                "idempotency_key",
                "metadata_",
                "quantity",
                "source",
                "subscription_item_id",
            ],
            "merge": [
                "event_ts",
                "feature_id",
                "idempotency_key",
                "metadata_",
                "quantity",
                "source",
                "subscription_item_id",
            ],
            "replace": [
                "event_ts",
                "feature_id",
                "idempotency_key",
                "metadata_",
                "quantity",
                "source",
                "subscription_item_id",
            ],
            "update": [
                "event_ts",
                "feature_id",
                "idempotency_key",
                "metadata_",
                "quantity",
                "source",
                "subscription_item_id",
            ],
        },
        "responses": {
            "list": [
                "event_ts",
                "feature_id",
                "idempotency_key",
                "metadata_",
                "quantity",
                "source",
                "subscription_item_id",
            ],
            "read": [
                "event_ts",
                "feature_id",
                "idempotency_key",
                "metadata_",
                "quantity",
                "source",
                "subscription_item_id",
            ],
        },
    },
    "usage_rollup": {
        "columns": [
            "subscription_item_id",
            "period_start",
            "period_end",
            "quantity_sum",
            "last_event_ts",
        ],
        "foreign_keys": [["subscription_item_id", "'subscription_items.id'"]],
        "requests": {
            "create": [
                "last_event_ts",
                "period_end",
                "period_start",
                "quantity_sum",
                "subscription_item_id",
            ],
            "merge": [
                "last_event_ts",
                "period_end",
                "period_start",
                "quantity_sum",
                "subscription_item_id",
            ],
            "replace": [
                "last_event_ts",
                "period_end",
                "period_start",
                "quantity_sum",
                "subscription_item_id",
            ],
            "update": [
                "last_event_ts",
                "period_end",
                "period_start",
                "quantity_sum",
                "subscription_item_id",
            ],
        },
        "responses": {
            "list": [
                "last_event_ts",
                "period_end",
                "period_start",
                "quantity_sum",
                "subscription_item_id",
            ],
            "read": [
                "last_event_ts",
                "period_end",
                "period_start",
                "quantity_sum",
                "subscription_item_id",
            ],
        },
    },
    "webhook_endpoint": {
        "columns": ["purpose", "account", "signing_secret", "active", "config"],
        "foreign_keys": [],
        "requests": {
            "create": ["account", "active", "config", "purpose", "signing_secret"],
            "merge": ["account", "active", "config", "purpose", "signing_secret"],
            "replace": ["account", "active", "config", "purpose", "signing_secret"],
            "update": ["account", "active", "config", "purpose", "signing_secret"],
        },
        "responses": {
            "list": ["account", "active", "config", "purpose", "signing_secret"],
            "read": ["account", "active", "config", "purpose", "signing_secret"],
        },
    },
}
