[project]
name = "swarmauri-experimental"
version = "0.6.2.dev3"
description = "This repository includes experimental components. (Inactive: experimental packages are now standalone.)"
authors = [
    { name = "Jacob Stewart", email = "jacob@swarmauri.com" },
]
license = "Apache-2.0"
readme = { file = "README.md", content-type = "text/markdown" }
repository = "http://github.com/swarmauri/swarmauri-sdk"
classifiers = [
    "Development Status :: 7 - Inactive",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
requires-python = ">=3.10,<3.13"

dependencies = [
    "swarmauri==0.5.3.dev5",
    "gensim",
    "neo4j",
    "numpy",
    "openai",
    "pydantic",
    "requests",
    "tensorflow",
    "torch",
    "transformers>=4.45.0",
    "typing_extensions",
]

[dependency-groups]
dev = [
    "flake8>=7.0",
    "pytest>=8.0",
    "pytest-asyncio>=0.24.0",
    "pytest-xdist>=3.6.1",
    "pytest-json-report>=1.5.0",
    "ruff>=0.9.9",
]

[tool.pytest.ini_options]
norecursedirs = ["combined", "scripts"]
markers = [
    "test: standard test",
    "unit: Unit tests",
    "integration: Integration tests",
    "acceptance: Acceptance tests",
    "experimental: Experimental tests",
]
log_cli = true
log_cli_level = "INFO"
log_cli_format = "%(asctime)s [%(levelname)s] %(message)s"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
asyncio_default_fixture_loop_scope = "function"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
