targets:
  # Main SDK packages
  - name: Core
    package: swarmauri_core
    search_path: /pkgs/core
    include:
      - swarmauri_core.*
    exclude:
      - "*.tests.*"
      - "*.experimental.*"

  - name: Base
    package: swarmauri_base
    search_path: /pkgs/base
    include:
      - swarmauri_base.*

  - name: Standard
    package: swarmauri_standard
    search_path: /pkgs/swarmauri_standard
    include:
      - swarmauri_standard.*

  # Discover all packages under standards
  - name: First Class
    search_path: /pkgs/standards
    include:
      - "*."  # all modules within discovered packages
    exclude:
      - "*.tests.*"

  # Discover all packages under community
  - name: Second Class
    search_path: /pkgs/community
    include:
      - "*."
    exclude:
      - "*.tests.*"

