"""Closure, interior, and fixpoint operators."""

from __future__ import annotations

from collections.abc import Callable, Iterable
from typing import TypeVar

from .core import Binary, Leq

T = TypeVar("T")
E = TypeVar("E")


def closure_step(step: Callable[[T], T], join: Binary[T]) -> Callable[[T], T]:
    """Make a step inflationary by joining input with ``step(input)``."""

    def inner(x: T) -> T:
        return join(x, step(x))

    return inner


def least_fixpoint(
    step: Callable[[T], T],
    bottom: T,
    *,
    max_steps: int = 10_000,
) -> T:
    """Kleene iteration from bottom until equality stabilizes."""

    cur = bottom
    for _ in range(max_steps):
        nxt = step(cur)
        if nxt == cur:
            return cur
        cur = nxt
    raise RuntimeError(f"least_fixpoint did not stabilize within {max_steps} steps")


def inflationary_fixpoint(
    step: Callable[[T], T],
    seed: T,
    join: Binary[T],
    *,
    max_steps: int = 10_000,
) -> T:
    """Iterate ``seed <- seed join step(seed)`` until stable."""

    return least_fixpoint(closure_step(step, join), seed, max_steps=max_steps)


def bounded_fixpoint(
    step: Callable[[T], T],
    seed: T,
    leq: Leq[T],
    *,
    max_steps: int = 10_000,
) -> T:
    """Iterate while asserting the chain is ascending."""

    cur = seed
    for _ in range(max_steps):
        nxt = step(cur)
        if not leq(cur, nxt):
            raise ValueError("step is not inflationary on the observed chain")
        if nxt == cur:
            return cur
        cur = nxt
    raise RuntimeError(f"bounded_fixpoint did not stabilize within {max_steps} steps")


def set_closure(seed: Iterable[E], expand: Callable[[E], Iterable[E]]) -> frozenset[E]:
    """Reachability-style closure over a finite graph generated by ``expand``."""

    seen = set(seed)
    frontier = list(seen)
    while frontier:
        item = frontier.pop()
        for nxt in expand(item):
            if nxt not in seen:
                seen.add(nxt)
                frontier.append(nxt)
    return frozenset(seen)


def closure_from_rules(
    seed: Iterable[E],
    rules: Iterable[Callable[[frozenset[E]], Iterable[E]]],
) -> frozenset[E]:
    """Least fixed point of positive inference rules over a finite fact set."""

    rule_tuple = tuple(rules)
    facts = frozenset(seed)
    while True:
        new = set(facts)
        for rule in rule_tuple:
            new.update(rule(facts))
        nxt = frozenset(new)
        if nxt == facts:
            return facts
        facts = nxt


def interior_fixpoint(step: Callable[[T], T], top: T, *, max_steps: int = 10_000) -> T:
    """Greatest-fixpoint-style iteration from top when ``step`` is deflationary."""

    cur = top
    for _ in range(max_steps):
        nxt = step(cur)
        if nxt == cur:
            return cur
        cur = nxt
    raise RuntimeError(f"interior_fixpoint did not stabilize within {max_steps} steps")


def compose_closures(*closures: Callable[[T], T]) -> Callable[[T], T]:
    """Iterate a finite family of closure operators until stable."""

    def combined(seed: T) -> T:
        cur = seed
        while True:
            nxt = cur
            for closure in closures:
                nxt = closure(nxt)
            if nxt == cur:
                return cur
            cur = nxt

    return combined
