[project]
name = "swm_example_community_package"
version = "0.6.2.dev3"
description = "example community package"
license = "Apache-2.0"
readme = "README.md"
repository = "http://github.com/swarmauri/swarmauri-sdk"
requires-python = ">=3.10,<3.13"
classifiers = [
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12"
]
authors = [{name = "Jacob Stewart", email = "jacob@swarmauri.com"}]
dependencies = ["swarmauri_core{'path': '../../core'}", "swarmauri_base{'path': '../../base'}"]

[tool.pytest.ini_options]
norecursedirs = ["combined", "scripts"]
markers = ["test: standard test", "unit: Unit tests", "i9n: Integration tests", "r8n: Regression tests", "timeout: mark test to timeout after X seconds", "xpass: Expected passes", "xfail: Expected failures", "acceptance: Acceptance tests"]
timeout = 300
log_cli = true
log_cli_level = "INFO"
log_cli_format = "%(asctime)s [%(levelname)s] %(message)s"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
asyncio_default_fixture_loop_scope = "function"

[tool.project.entry-points."swarmauri.agents"]
ExampleCommunityAgent = "swm_example_community_package.ExampleCommunityAgent:ExampleCommunityAgent"
[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = ["pytest>=8.0", "pytest-asyncio>=0.24.0", "pytest-xdist>=3.6.1", "pytest-json-report>=1.5.0", "python-dotenv", "requests>=2.32.3", "flake8>=7.0"]
