"""init

Revision ID: 1654e69ea52e
Revises:
Create Date: 2025-06-10 02:26:26.760815

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1654e69ea52e"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create enum type only if it doesn't already exist
    op.execute("""
    DO $$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'status') THEN
            CREATE TYPE status AS ENUM ('pending', 'dispatched', 'running', 'success', 'failed', 'cancelled');
        END IF;
    END
    $$;
    """)

    # Create table
    op.create_table(
        "task_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("pool", sa.String(), nullable=True),
        sa.Column("task_type", sa.String(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "dispatched",
                "running",
                "success",
                "failed",
                "cancelled",
                name="status",
            ),
            nullable=True,
        ),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("deps", sa.JSON(), nullable=False),
        sa.Column("edge_pred", sa.String(), nullable=True),
        sa.Column("labels", sa.JSON(), nullable=False),
        sa.Column("config_toml", sa.String(), nullable=True),
        sa.Column("artifact_uri", sa.String(), nullable=True),
        sa.Column("started_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("finished_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("task_runs")
    # ### end Alembic commands ###
