[project]
name = "swarmauri_middleware_auth"
version = "0.6.2.dev2"
description = "Middleware for handling authentication in Swarmauri applications."
license = "Apache-2.0"
readme = "README.md"
requires-python = ">=3.10,<3.13"
authors = [{ name = "Jacob Stewart", email = "jacob@swarmauri.com" }]
classifiers = [
    "License :: OSI Approved :: Apache Software License",
    "Natural Language :: English",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Development Status :: 3 - Alpha",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Internet :: WWW/HTTP :: HTTP Servers",
    "Topic :: Internet :: WWW/HTTP :: Middleware",
    "Intended Audience :: Developers",
]
dependencies = [
    "swarmauri_core",
    "swarmauri_base",
    "swarmauri_standard",
    "fastapi",
    "PyJWT",
]

[tool.uv.sources]
swarmauri_core = { workspace = true }
swarmauri_base = { workspace = true }
swarmauri_standard = { workspace = true }

[tool.pytest.ini_options]
norecursedirs = ["combined", "scripts"]
markers = [
    "test: standard test",
    "unit: Unit tests",
    "i9n: Integration tests",
    "r8n: Regression tests",
    "timeout: mark test to timeout after X seconds",
    "xpass: Expected passes",
    "xfail: Expected failures",
    "acceptance: Acceptance tests",
    "perf: Performance tests that measure execution time and resource usage",
]
timeout = 300
log_cli = true
log_cli_level = "INFO"
log_cli_format = "%(asctime)s [%(levelname)s] %(message)s"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
asyncio_default_fixture_loop_scope = "function"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest>=8.0",
    "pytest-asyncio>=0.24.0",
    "pytest-xdist>=3.6.1",
    "pytest-json-report>=1.5.0",
    "flake8>=7.0",
    "ruff>=0.9.9",
    "pytest-timeout>=2.3.1",
    "pytest-benchmark>=4.0.0",
]

[project.entry-points.'swarmauri.middlewares']
AuthMiddleware = "swarmauri_middleware_auth:AuthMiddleware"
