name: Nightly Benchmarks

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install prometheus-client httpx

      - name: Run benchmarks
        run: python benchmarks/bench_runner.py --baseline benchmarks/baseline.csv

      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: bench-results
          path: benchmarks/results.csv
