name: check-missing-tests

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'pkgs/**'
      - 'scripts/check_test_files.py'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Run missing test check
        run: python scripts/check_test_files.py
