name: Deploy Docs Apps
on:
  push:
    branches: [master, mono/dev]
    paths:
      - 'docs/**'
      - 'pkgs/**'
  workflow_dispatch:

jobs:
  deploy-apps:
    runs-on: [docs]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Restart zdx services
        run: |
          docker compose -f infra/docs/docker-compose.yaml \
          up -d --build --force-recreate --no-deps \
          swarmauri-sdk-docs peagen-docs tigrbl-docs
