name: v0.7.0 - Test Integrity Check

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'pkgs/**'
  workflow_dispatch:

jobs:
  test-integrity-check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Run Test Files Integrity Check
        run: python ./scripts/test_files_integrity_check.py